### ISSUE TITLE
Can i  redefine message.self () function in puppet？i  need to do something. 

### ISSUE THREAD

**Issue by goldcome** [wechaty/puppet#175]
Can i  redefine message.self () function in puppet？i  need to do something.

**Comment by huan** [comment]
Please feel free to submit an issue to description what you want to do in detail.

And also you can submit a PR to demonstrate what you need to change as well.

Thanks.

**Comment by goldcome** [comment]
I want to write puppet with the http plugin of [keaimao](http://www.keaimao.com.cn/forum.php), it supports multiple accounts,  I don't know how to define the login id，if i want to support multiple accounts.

**Comment by huan** [comment]
It's great to know that you want to implement a new puppet with Keaimo!

From our current design of the Puppet system, the best practice is to use one puppet for one account.

So if you want to support multiple accounts, you can use multiple Puppet/Wechaty to achieve that.

For your easy getting started, I'd like to suggest that you can finish a one account version first, then it will be very easy to extend to multiple accounts.

**Comment by goldcome** [comment]
Ok, thank you for your reply.

**Comment by huan** [comment]
You are welcome.

Please let me know if you have any updates on your new Puppet implementation!
