### ISSUE TITLE
the app will exit with error of messageRawPayloadParser function.

### ISSUE THREAD

**Issue by goldcome** [wechaty/puppet#176]
I want to work fine when the error occurs with the messageRawPayloadParser function，try catch not work，it must be return fromId and toId，what should I do to interrupt it.

**Comment by huan** [comment]
If you are implementing your own puppet, then you should override this function for your own logic.

If this is a problem when you are using the existing puppet, please provide more details.

**Comment by goldcome** [comment]
Close it，this design is not problem.
