### ISSUE TITLE
How can we get the state of the puppet with new API?

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet#177]
Since ```this.state.on()``` or ```this.state.off()``` no longer works?

**Comment by huan** [comment]
Use active / inactive instead

**Comment by hcfw007** [comment]
Should puppet implementation manipulate these states?

**Comment by huan** [comment]
With v1.x , those states is manipulated by the puppet base class and should not mutated by the child class any more.

**Comment by hcfw007** [comment]
Cool, thanks for the explanation.

**Comment by huan** [comment]
You are welcome.
