### ISSUE TITLE
Helpers export

### ISSUE THREAD

**Issue by hcfw007** [wechaty/puppet#178]
I am reading the code of latest wechaty-puppet recently and noticed you replace exports of helpers module with resolve puppet function. I'm wondering in that case how could we import logs and file-box and other helper modules.

Also sometimes we also need to use FileBoxType enum. Maybe we should also export that? I currently install File-Box separately but  it would be great if you can export that inside wechaty-puppet.

**Comment by huan** [comment]
Export those from wechaty-puppet is not a good practice because you can always have them as your local dependency and import them directly:

```ts
import { FileBox } from 'file-box'
```

The reason of we export them from wechaty-puppet before is because the `instanceof` problem: different version of FileBox instances have different Constructor class. We have solve this problem in the latest version of our modules and that's why we remove this re-export.

**Comment by hcfw007** [comment]
Thank you for you explanation about file-box, that's exactly what I did updating puppet-wxwork. I was worried I did it wrong.

But I still have problem about export of helpers in wechaty 1.11.x. Besides file-box, helpers also exports useful modules like log. The 1.11.x version helper module only exports resolvePuppet function.

**Comment by huan** [comment]
If you follow my suggestion:

BTW: I'd like to suggest that you can always read the official puppet providers source code like wechaty-puppet-service, to learn about the best practice of wechaty v1.x

Then you can find that the log can be import-ed from `wechaty-puppet` like this:

https://github.com/wechaty/puppet-service/blob/1e4721f0a53c4b3453cf61cf72ea0113d93494f9/src/config.ts#L3

And you can always import log from `brolog` directly:

```ts
import { log } from 'brolog'
```

The difference between them is:

- if you import log from `wechaty-puppet`, then the `WECHATY_LOG` environment variable will be set to the log.
- if you import log from `brolog`, then it will not take the `WECHATY_LOG` settings.
