### ISSUE TITLE
`roomMemberSearch` still use legacy `this.id` as user id

### ISSUE THREAD

**Issue by padlocal** [wechaty/puppet#197]
Since `this.id` has been replaced by `currentUserId` for puppet to get signed-on user id. So the following code will return uuid of the puppet, which will cause unexpceted behaviors.

https://github.com/wechaty/puppet/blob/38c5b17b405a86fcbc52d4c4363a15c234708548/src/mixins/room-member-mixin.ts#L42-L44

https://github.com/wechaty/puppet/blob/38c5b17b405a86fcbc52d4c4363a15c234708548/src/mixins/room-member-mixin.ts#L53-L55

**Comment by huan** [comment]
Good catch!

Thank you very much!
